### PR TITLE
Add passing code to practice typing code

### PR DESCRIPTION
**Pull request by adamryman**
```
$ gotypist -c -w $GOPATH/src/github.com/pb-/gotypist/main.go
```
```
    Score: 0
    Level: 0
 Progress: 0%





                                         In fast mode
                          (type as fast as you can, ignore mistakes!)


                          flag.Parse() if _, ok := timeouts[t]; !ok {⏎



                                      0 errors   0.0 seconds






 What's this fast, slow, medium thing?!
 http://steve-yegge.blogspot.com/2008/09/programmings-dirtiest-little-secret.html
```

### CODE REVIEW

**Comment by pb-** [comment]
Thanks again for contributing! :confetti_ball: 

How do you feel about turning this PR into something like
```
-l FILE
  use lines from FILE
```
That way it would be more general and one could learn typing coherent lines of code (or of something else).

**Comment by adamryman** [comment]
That sounds good to me.

I will try to add that logic, doing this got me closer to what I wanted, though what you are saying sounds much more useful.

Thanks for the Unlicense! :open_file_folder: :open_hands: :book: I'll be sure to point more people here.

**Comment by pb-** [comment]
I actually started to rework that phrase generation part - it is something I planned to do anyway. I often add custom logic to learn specific phrases and what I have in mind will make this much easier and more flexible. You may want to wait for that before spending more time :slightly_smiling_face:.

**Comment by adamryman** [comment]
Ok, I will wait for you to do your thing.

Feel free to implement
```
-l FILE
  use lines from FILE
```

Yourself if you feel like it, as I imagine it would be pretty easy to roll into your current work.

I'll be playing with this a lot this week I'm sure.

I'm going to close this for now and create an issue in its place. Drop a comment in there if you are not going to get to it.

**Comment by adamryman** [comment]
Continued on #6

**Pull request closed without merging**
